package com.example.callof.modelo;

// default package
// Generated 17-abr-2020 4:27:13 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Investigador generated by hbm2java
 */
@Entity
@Table(name = "investigador", catalog = "db_servidor")
public class Investigador implements java.io.Serializable {

	private String nombreCompleto;
	private String profesion;
	private String lugarNacimiento;
	private String idCaracteristicas;
	private String idTrastornos;
	private String sexo;
	private Integer edad;

	public Investigador() {
	}

	public Investigador(String nombreCompleto, String profesion, String lugarNacimiento, String idCaracteristicas,
			String idTrastornos) {
		this.nombreCompleto = nombreCompleto;
		this.profesion = profesion;
		this.lugarNacimiento = lugarNacimiento;
		this.idCaracteristicas = idCaracteristicas;
		this.idTrastornos = idTrastornos;
	}

	public Investigador(String nombreCompleto, String profesion, String lugarNacimiento, String idCaracteristicas,
			String idTrastornos, String sexo, Integer edad) {
		this.nombreCompleto = nombreCompleto;
		this.profesion = profesion;
		this.lugarNacimiento = lugarNacimiento;
		this.idCaracteristicas = idCaracteristicas;
		this.idTrastornos = idTrastornos;
		this.sexo = sexo;
		this.edad = edad;
	}

	@Id

	@Column(name = "NombreCompleto", unique = true, nullable = false, length = 50)
	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	@Column(name = "Profesion", nullable = false, length = 50)
	public String getProfesion() {
		return this.profesion;
	}

	public void setProfesion(String profesion) {
		this.profesion = profesion;
	}

	@Column(name = "Lugar_Nacimiento", nullable = false, length = 50)
	public String getLugarNacimiento() {
		return this.lugarNacimiento;
	}

	public void setLugarNacimiento(String lugarNacimiento) {
		this.lugarNacimiento = lugarNacimiento;
	}

	@Column(name = "id_caracteristicas", nullable = false, length = 10)
	public String getIdCaracteristicas() {
		return this.idCaracteristicas;
	}

	public void setIdCaracteristicas(String idCaracteristicas) {
		this.idCaracteristicas = idCaracteristicas;
	}

	@Column(name = "id_trastornos", nullable = false, length = 10)
	public String getIdTrastornos() {
		return this.idTrastornos;
	}

	public void setIdTrastornos(String idTrastornos) {
		this.idTrastornos = idTrastornos;
	}

	@Column(name = "Sexo", length = 7)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "Edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

}
