package com.example.callof.modelo;

// default package
// Generated 17-abr-2020 4:27:13 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Objetos generated by hbm2java
 */
@Entity
@Table(name = "lugarnacimiento", catalog = "db_servidor")
public class LugarNacimiento implements java.io.Serializable {

	private int id_lugarnac;
	private String lugarnac;

	public LugarNacimiento() {
	}

	public LugarNacimiento(int id_lugarnac) {
		this.id_lugarnac = id_lugarnac;
	}

	public LugarNacimiento(int id_lugarnac, String lugarnac) {
		this.id_lugarnac = id_lugarnac;
		this.lugarnac = lugarnac;
	}

	@Id

	@Column(name = "id_lugarnac", unique = true, nullable = false)
	public int getId_LugarNac() {
		return this.id_lugarnac;
	}

	public void setId_LugarNac(int idNombre) {
		this.id_lugarnac = idNombre;
	}

	@Column(name = "lugarnac", length = 50)
	public String getLugarNac() {
		return this.lugarnac;
	}

	public void setLugarNac(String nombre) {
		this.lugarnac = nombre;
	}

	
}

