package com.example.callof.modelo;

// default package
// Generated 17-abr-2020 4:27:13 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Objetos generated by hbm2java
 */
@Entity
@Table(name = "Nombres", catalog = "db_servidor")
public class Nombres implements java.io.Serializable {

	private int idNombre;
	private String nombre;

	public Nombres() {
	}

	public Nombres(int idNombre) {
		this.idNombre = idNombre;
	}

	public Nombres(int idNombre, String nombre) {
		this.idNombre = idNombre;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "id_nombre", unique = true, nullable = false)
	public int getIdNombre() {
		return this.idNombre;
	}

	public void setIdNombre(int idNombre) {
		this.idNombre = idNombre;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	
}

