package com.example.callof.modelo;

// default package
// Generated 17-abr-2020 4:27:13 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Trastornos generated by hbm2java
 */
@Entity
@Table(name = "trastornos", catalog = "db_servidor")
public class Trastornos implements java.io.Serializable {

	private String idTrastornos;
	private Boolean trastorno1;
	private Boolean trastorno2;
	private Boolean trastorno3;
	private Boolean trastorno4;
	private Boolean trastorno5;
	private Boolean trastorno6;

	public Trastornos() {
	}

	public Trastornos(String idTrastornos) {
		this.idTrastornos = idTrastornos;
	}

	public Trastornos(String idTrastornos, Boolean trastorno1, Boolean trastorno2, Boolean trastorno3,
			Boolean trastorno4, Boolean trastorno5, Boolean trastorno6) {
		this.idTrastornos = idTrastornos;
		this.trastorno1 = trastorno1;
		this.trastorno2 = trastorno2;
		this.trastorno3 = trastorno3;
		this.trastorno4 = trastorno4;
		this.trastorno5 = trastorno5;
		this.trastorno6 = trastorno6;
	}

	@Id

	@Column(name = "id_trastornos", unique = true, nullable = false, length = 10)
	public String getIdTrastornos() {
		return this.idTrastornos;
	}

	public void setIdTrastornos(String idTrastornos) {
		this.idTrastornos = idTrastornos;
	}

	@Column(name = "trastorno_1")
	public Boolean getTrastorno1() {
		return this.trastorno1;
	}

	public void setTrastorno1(Boolean trastorno1) {
		this.trastorno1 = trastorno1;
	}

	@Column(name = "trastorno_2")
	public Boolean getTrastorno2() {
		return this.trastorno2;
	}

	public void setTrastorno2(Boolean trastorno2) {
		this.trastorno2 = trastorno2;
	}

	@Column(name = "trastorno_3")
	public Boolean getTrastorno3() {
		return this.trastorno3;
	}

	public void setTrastorno3(Boolean trastorno3) {
		this.trastorno3 = trastorno3;
	}

	@Column(name = "trastorno_4")
	public Boolean getTrastorno4() {
		return this.trastorno4;
	}

	public void setTrastorno4(Boolean trastorno4) {
		this.trastorno4 = trastorno4;
	}

	@Column(name = "trastorno_5")
	public Boolean getTrastorno5() {
		return this.trastorno5;
	}

	public void setTrastorno5(Boolean trastorno5) {
		this.trastorno5 = trastorno5;
	}

	@Column(name = "trastorno_6")
	public Boolean getTrastorno6() {
		return this.trastorno6;
	}

	public void setTrastorno6(Boolean trastorno6) {
		this.trastorno6 = trastorno6;
	}

}
